# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions의 빌드 환경

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17  # 원하는 Java 버전
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/*.jar  # 빌드된 JAR 파일 경로

  deploy:
    runs-on: ubuntu-latest
    needs: build  # build 작업이 완료되면 실행
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-jar

      - name: Copy to RockyOS server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          scp -i /tmp/ssh_key -o StrictHostKeyChecking=no build/libs/*.jar user@rockyos-instance:/path/to/deploy/

      - name: Run app on RockyOS server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no user@rockyos-instance << EOF
          cd /path/to/deploy/
          # 기존 애플리케이션 중지
          pkill -f 'java -jar'
          # 새 JAR 파일 실행
          nohup java -jar app.jar > app.log 2>&1 &
          EOF
