# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions의 빌드 환경

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # 전체 커밋 기록 가져오기

      - name: Set up JDK 17  # 원하는 Java 버전
        uses: actions/setup-java@v4  # 최신 버전으로 업데이트
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle Wrapper
        run: cd ./survwey/survwey && chmod +x ./gradlew

      - name: Build with Gradle
        run: cd ./survwey/survwey && ./gradlew build -x test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: survwey/survwey/build/libs/*.jar  # 빌드된 JAR 파일 경로

  deploy:
    runs-on: ubuntu-latest
    needs: build  # build 작업이 완료되면 실행
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-jar

      - name: Copy to RockyOS server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          scp -i /tmp/ssh_key -o StrictHostKeyChecking=no survwey/survwey/build/libs/*.jar intern2team@218.55.79.80:/home/intern2team

      - name: Run app on RockyOS server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DB_URL: ${{ secrets.DB_URL }}  # GitHub Secrets에서 DB_URL을 가져옴
          DB_USERNAME: ${{ secrets.DB_USERNAME }}  # GitHub Secrets에서 DB_USERNAME을 가져옴
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}  # GitHub Secrets에서 DB_PASSWORD를 가져옴
        run: |
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no intern2team@218.55.79.80 << EOF
          cd /home/intern2team
          
          # 기존 애플리케이션 중지
          pkill -f 'java -jar'
          
          # 새 JAR 파일 실행
          nohup java -jar survwey-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          
          # DB 연결 시 환경 변수를 사용하여 연결
          # 예: DB_HOST, DB_PORT, DB_USER, DB_PASSWORD를 활용하여 DB 연결
          EOF
